/**
 * ReportPDFDocument Component
 * 
 * This component generates a PDF document structure for reports using @react-pdf/renderer.
 * It creates a formatted PDF with header, summary, data table, charts, and footer.
 * 
 * Features:
 * - PDF document structure with A4 page size
 * - Report header with title and metadata
 * - Summary section with key metrics
 * - Data table with role-specific columns
 * - Chart images display (captured from ReportViewer)
 * - Footer with generation timestamp and "Generated by SLIIT"
 * - Responsive table layout for different report types
 * 
 * Props:
 * - reportData: Object containing report data (reportType, filters, summary, tableData)
 * - chartImages: Array of base64 image strings (optional) - Chart images captured from ReportViewer
 * 
 * Report Types Supported:
 * - task-assignment: Shows task-specific columns (Task Name, Staff Name, Domain, Hours, Method)
 * - Other reports: Shows staff-specific columns (Staff, Domain, Tasks, Hours breakdown, Status)
 * 
 * PDF Structure:
 * 1. Header: Report title, academic period, semester, generation date
 * 2. Summary: Hours assigned, teaching/admin/research percentages, overload status
 * 3. Data Table: Report data in tabular format
 * 4. Charts: Chart images if provided
 * 5. Footer: "Generated by SLIIT" with timestamp
 * 
 * Dependencies:
 * - @react-pdf/renderer: For PDF generation
 */
// Import React for component creation
import React from 'react';
// Import PDF rendering components from @react-pdf/renderer
import { Document, Page, Text, View, StyleSheet, Image } from '@react-pdf/renderer';

/**
 * PDF Styles
 * Defines styling for all PDF elements including:
 * - Page layout and padding
 * - Header and title styling
 * - Table structure and cell formatting
 * - Chart container styling
 * - Footer positioning
 */
/**
 * PDF Styles Object
 * Defines all styling for PDF elements using StyleSheet.create from @react-pdf/renderer
 * Styles are similar to CSS but use camelCase and specific PDF-compatible properties
 */
const styles = StyleSheet.create({
  // Page container style - main page layout
  page: {
    flexDirection: 'column', // Arrange children vertically
    backgroundColor: '#FFFFFF', // White background
    padding: 30, // 30pt padding on all sides
    fontSize: 10, // Default font size 10pt
    fontFamily: 'Helvetica', // Font family for PDF text
  },
  // Header section style - report header container
  header: {
    marginBottom: 20, // 20pt bottom margin
    borderBottom: '2 solid #000000', // 2pt solid black bottom border
    paddingBottom: 10, // 10pt bottom padding
  },
  // Title text style - report title
  title: {
    fontSize: 20, // Large 20pt font size
    fontWeight: 'bold', // Bold text weight
    marginBottom: 10, // 10pt bottom margin
    textAlign: 'center', // Center-aligned text
  },
  // Metadata text style - report metadata (date, period, etc.)
  metadata: {
    marginBottom: 5, // 5pt bottom margin
    fontSize: 9, // 9pt font size (smaller than default)
    color: '#666666', // Gray color for metadata
  },
  // Section container style - container for major sections
  section: {
    marginTop: 15, // 15pt top margin
    marginBottom: 10, // 10pt bottom margin
  },
  // Section title style - section heading text
  sectionTitle: {
    fontSize: 14, // 14pt font size
    fontWeight: 'bold', // Bold text weight
    marginBottom: 8, // 8pt bottom margin
  },
  // Summary box style - container for summary key-value pairs
  summaryBox: {
    flexDirection: 'row', // Arrange children horizontally
    justifyContent: 'space-between', // Space items apart
    marginBottom: 5, // 5pt bottom margin
    padding: 5, // 5pt padding on all sides
    backgroundColor: '#F5F5F5', // Light gray background
  },
  // Summary label style - left side of summary box (label text)
  summaryLabel: {
    fontWeight: 'bold', // Bold text weight
    width: '50%', // Take up 50% of container width
  },
  // Summary value style - right side of summary box (value text)
  summaryValue: {
    width: '50%', // Take up 50% of container width
  },
  // Table container style - main table wrapper
  table: {
    display: 'table', // Table display type
    width: 'auto', // Auto width based on content
    borderStyle: 'solid', // Solid border style
    borderWidth: 1, // 1pt border width
    borderRightWidth: 0, // No right border (handled by cells)
    borderBottomWidth: 0, // No bottom border (handled by cells)
    marginTop: 10, // 10pt top margin
  },
  // Table row style - individual table row container
  tableRow: {
    margin: 'auto', // Auto margins
    flexDirection: 'row', // Arrange cells horizontally
  },
  // Table column header style - header cell for 8-column layout (12.5% each)
  tableColHeader: {
    width: '12.5%', // 12.5% width (1/8 of table width for 8 columns)
    borderStyle: 'solid', // Solid border style
    borderWidth: 1, // 1pt border width
    borderLeftWidth: 0, // No left border (prevents double borders)
    borderTopWidth: 0, // No top border (prevents double borders)
    backgroundColor: '#F0F0F0', // Light gray background for headers
    padding: 5, // 5pt padding on all sides
  },
  // Table column header wide style - header cell for 6-column layout (16.67% each)
  tableColHeaderWide: {
    width: '16.67%', // 16.67% width (1/6 of table width for 6 columns)
    borderStyle: 'solid', // Solid border style
    borderWidth: 1, // 1pt border width
    borderLeftWidth: 0, // No left border (prevents double borders)
    borderTopWidth: 0, // No top border (prevents double borders)
    backgroundColor: '#F0F0F0', // Light gray background for headers
    padding: 5, // 5pt padding on all sides
  },
  // Table column style - data cell for 8-column layout (12.5% each)
  tableCol: {
    width: '12.5%', // 12.5% width (1/8 of table width for 8 columns)
    borderStyle: 'solid', // Solid border style
    borderWidth: 1, // 1pt border width
    borderLeftWidth: 0, // No left border (prevents double borders)
    borderTopWidth: 0, // No top border (prevents double borders)
    padding: 5, // 5pt padding on all sides
  },
  // Table column wide style - data cell for 6-column layout (16.67% each)
  tableColWide: {
    width: '16.67%', // 16.67% width (1/6 of table width for 6 columns)
    borderStyle: 'solid', // Solid border style
    borderWidth: 1, // 1pt border width
    borderLeftWidth: 0, // No left border (prevents double borders)
    borderTopWidth: 0, // No top border (prevents double borders)
    padding: 5, // 5pt padding on all sides
  },
  // Table cell header style - text inside header cells
  tableCellHeader: {
    fontSize: 8, // 8pt font size (small for table headers)
    fontWeight: 'bold', // Bold text weight
    textAlign: 'center', // Center-aligned text
  },
  // Table cell style - text inside data cells
  tableCell: {
    fontSize: 8, // 8pt font size (small for table data)
    textAlign: 'left', // Left-aligned text
  },
  // Chart container style - container for chart images
  chartContainer: {
    marginTop: 10, // 10pt top margin
    marginBottom: 15, // 15pt bottom margin
    alignItems: 'center', // Center-align chart horizontally
    pageBreakInside: 'avoid', // Prevent page break inside chart container
  },
  // Chart image style - styling for chart image elements
  chartImage: {
    maxWidth: 500, // Maximum width 500pt
    maxHeight: 300, // Maximum height 300pt
    objectFit: 'contain', // Scale image to fit while maintaining aspect ratio
  },
  // Footer style - footer text at bottom of page
  footer: {
    position: 'absolute', // Absolute positioning
    bottom: 30, // 30pt from bottom
    left: 30, // 30pt from left
    right: 30, // 30pt from right
    textAlign: 'center', // Center-aligned text
    fontSize: 8, // 8pt font size (small for footer)
    color: '#666666', // Gray color for footer text
    borderTop: '1 solid #CCCCCC', // 1pt solid light gray top border
    paddingTop: 10, // 10pt top padding
  },
});

// Component function that receives props via destructuring
const ReportPDFDocument = ({ reportData, chartImages }) => {
  /**
   * Destructure reportData object to extract individual properties
   * - reportType: String - Type of report (e.g., 'task-assignment', 'staff-workload-summary')
   * - filters: Object - Filter parameters (semester, academicPeriod, etc.)
   * - summary: Object - Summary metrics (hoursAssigned, percentages, overload status)
   * - tableData: Array - Array of data objects for table rows
   */
  const { reportType, filters, summary, tableData } = reportData;

  /**
   * Function: getReportTitle
   * Returns the display title for the current report type
   * Maps report type IDs to human-readable titles
   * @returns {string} - Report title string
   */
  const getReportTitle = () => {
    // Object mapping report type IDs to display titles
    const titles = {
      'staff-workload-summary': 'Staff Workload Summary', // Staff workload summary report
      'program-teaching-load': 'Program Teaching Load Report', // Program teaching load report
      'task-assignment': 'Task Assignment Report', // Task assignment report
      'underload-overload': 'Underload/Overload Report', // Underload/overload report
      'ga-optimization': 'GA Optimization Output Report', // GA optimization report
      'change-requests': 'Change Requests Report', // Change requests report
      'module-teaching': 'Module-Level Teaching Report', // Module teaching report
      'staff-activity': 'Staff Activity Report' // Staff activity report
    };
    // Return title for current report type, or 'Report' as fallback
    return titles[reportType] || 'Report';
  };

  /**
   * Computed: isTaskAssignment
   * Boolean indicating if current report is a task-assignment report
   * Used to determine which table columns to display
   */
  // Check if report type is 'task-assignment'
  const isTaskAssignment = reportType === 'task-assignment';

  // Return JSX structure for PDF document
  return (
    // Document root component - wraps entire PDF
    <Document>
      {/* Page component - A4 size page */}
      <Page size="A4" style={styles.page}>
        {/* Header section with title and metadata */}
        <View style={styles.header}>
          {/* Report title (dynamically generated based on report type) */}
          <Text style={styles.title}>{getReportTitle()}</Text>
          {/* Academic period metadata */}
          <Text style={styles.metadata}>Academic Period: {filters.academicPeriod || 'N/A'}</Text>
          {/* Semester metadata */}
          <Text style={styles.metadata}>Semester: {filters.semester}</Text>
          {/* Generation timestamp metadata */}
          <Text style={styles.metadata}>Generated: {new Date().toLocaleString()}</Text>
        </View>

        {/* Summary section */}
        <View style={styles.section}>
          {/* Section title */}
          <Text style={styles.sectionTitle}>Summary</Text>
          {/* Hours Assigned summary box */}
          <View style={styles.summaryBox}>
            {/* Label text */}
            <Text style={styles.summaryLabel}>Hours Assigned:</Text>
            {/* Value display with 'h' suffix */}
            <Text style={styles.summaryValue}>{summary.hoursAssigned}h</Text>
          </View>
          {/* Teaching percentage summary box */}
          <View style={styles.summaryBox}>
            {/* Label text */}
            <Text style={styles.summaryLabel}>Teaching:</Text>
            {/* Value display with '%' suffix */}
            <Text style={styles.summaryValue}>{summary.teachingPercent}%</Text>
          </View>
          {/* Admin percentage summary box */}
          <View style={styles.summaryBox}>
            {/* Label text */}
            <Text style={styles.summaryLabel}>Admin:</Text>
            {/* Value display with '%' suffix */}
            <Text style={styles.summaryValue}>{summary.adminPercent}%</Text>
          </View>
          {/* Research percentage summary box */}
          <View style={styles.summaryBox}>
            {/* Label text */}
            <Text style={styles.summaryLabel}>Research:</Text>
            {/* Value display with '%' suffix */}
            <Text style={styles.summaryValue}>{summary.researchPercent}%</Text>
          </View>
          {/* Overload status summary box */}
          <View style={styles.summaryBox}>
            {/* Label text */}
            <Text style={styles.summaryLabel}>Overload:</Text>
            {/* Value display: 'Yes' or 'No' based on overload boolean */}
            <Text style={styles.summaryValue}>{summary.overload ? 'Yes' : 'No'}</Text>
          </View>
        </View>

        {/* Conditional rendering: Show table section if tableData exists */}
        {tableData.length > 0 && (
          <View style={styles.section}>
            {/* Section title */}
            <Text style={styles.sectionTitle}>Report Data</Text>
            {/* Table container */}
            <View style={styles.table}>
              {/* Table Header Row */}
              <View style={styles.tableRow}>
                {/* Conditional rendering: Different column headers for task-assignment vs other reports */}
                {isTaskAssignment ? (
                  // Task assignment report columns (6 columns, 16.67% width each)
                  <>
                    {/* Task Name column header */}
                    <View style={styles.tableColHeaderWide}>
                      <Text style={styles.tableCellHeader}>Task Name</Text>
                    </View>
                    {/* Staff Name column header */}
                    <View style={styles.tableColHeaderWide}>
                      <Text style={styles.tableCellHeader}>Staff Name</Text>
                    </View>
                    {/* Domain column header */}
                    <View style={styles.tableColHeaderWide}>
                      <Text style={styles.tableCellHeader}>Domain</Text>
                    </View>
                    {/* Hours per Week column header */}
                    <View style={styles.tableColHeaderWide}>
                      <Text style={styles.tableCellHeader}>Hrs/Week</Text>
                    </View>
                    {/* Total Hours column header */}
                    <View style={styles.tableColHeaderWide}>
                      <Text style={styles.tableCellHeader}>Total Hrs</Text>
                    </View>
                    {/* Assignment Method column header */}
                    <View style={styles.tableColHeaderWide}>
                      <Text style={styles.tableCellHeader}>Method</Text>
                    </View>
                  </>
                ) : (
                  // Other report types columns (8 columns, 12.5% width each)
                  <>
                    {/* Staff column header */}
                    <View style={styles.tableColHeader}>
                      <Text style={styles.tableCellHeader}>Staff</Text>
                    </View>
                    {/* Domain column header */}
                    <View style={styles.tableColHeader}>
                      <Text style={styles.tableCellHeader}>Domain</Text>
                    </View>
                    {/* Tasks column header */}
                    <View style={styles.tableColHeader}>
                      <Text style={styles.tableCellHeader}>Tasks</Text>
                    </View>
                    {/* Total Hours column header */}
                    <View style={styles.tableColHeader}>
                      <Text style={styles.tableCellHeader}>Total</Text>
                    </View>
                    {/* Teaching Hours column header */}
                    <View style={styles.tableColHeader}>
                      <Text style={styles.tableCellHeader}>Teaching</Text>
                    </View>
                    {/* Admin Hours column header */}
                    <View style={styles.tableColHeader}>
                      <Text style={styles.tableCellHeader}>Admin</Text>
                    </View>
                    {/* Research Hours column header */}
                    <View style={styles.tableColHeader}>
                      <Text style={styles.tableCellHeader}>Research</Text>
                    </View>
                    {/* Status column header */}
                    <View style={styles.tableColHeader}>
                      <Text style={styles.tableCellHeader}>Status</Text>
                    </View>
                  </>
                )}
              </View>

              {/* Table Data Rows */}
              {/* Map over tableData array to create table rows */}
              {tableData.map((row, index) => (
                // Table row for each data item
                <View key={index} style={styles.tableRow}>
                  {/* Conditional rendering: Different cell content for task-assignment vs other reports */}
                  {isTaskAssignment ? (
                    // Task assignment report cells (6 columns, 16.67% width each)
                    <>
                      {/* Task Name cell */}
                      <View style={styles.tableColWide}>
                        <Text style={styles.tableCell}>{row.taskName || 'N/A'}</Text>
                      </View>
                      {/* Staff Name cell */}
                      <View style={styles.tableColWide}>
                        <Text style={styles.tableCell}>{row.staffName || 'N/A'}</Text>
                      </View>
                      {/* Domain cell */}
                      <View style={styles.tableColWide}>
                        <Text style={styles.tableCell}>{row.domain || 'N/A'}</Text>
                      </View>
                      {/* Hours per Week cell */}
                      <View style={styles.tableColWide}>
                        <Text style={styles.tableCell}>{row.hoursPerWeek || 0}</Text>
                      </View>
                      {/* Total Hours cell */}
                      <View style={styles.tableColWide}>
                        <Text style={styles.tableCell}>{row.totalHours || 0}</Text>
                      </View>
                      {/* Assignment Method cell */}
                      <View style={styles.tableColWide}>
                        <Text style={styles.tableCell}>{row.assignmentMethod || 'Manual'}</Text>
                      </View>
                    </>
                  ) : (
                    // Other report types cells (8 columns, 12.5% width each)
                    <>
                      {/* Staff Name cell */}
                      <View style={styles.tableCol}>
                        <Text style={styles.tableCell}>{row.staffName || 'N/A'}</Text>
                      </View>
                      {/* Domain cell */}
                      <View style={styles.tableCol}>
                        <Text style={styles.tableCell}>{row.domain || 'N/A'}</Text>
                      </View>
                      {/* Number of Tasks cell */}
                      <View style={styles.tableCol}>
                        <Text style={styles.tableCell}>{row.tasks || 0}</Text>
                      </View>
                      {/* Total Hours cell */}
                      <View style={styles.tableCol}>
                        <Text style={styles.tableCell}>{row.totalHours || 0}</Text>
                      </View>
                      {/* Teaching Hours cell */}
                      <View style={styles.tableCol}>
                        <Text style={styles.tableCell}>{row.teachingHours || 0}</Text>
                      </View>
                      {/* Admin Hours cell */}
                      <View style={styles.tableCol}>
                        <Text style={styles.tableCell}>{row.adminHours || 0}</Text>
                      </View>
                      {/* Research Hours cell */}
                      <View style={styles.tableCol}>
                        <Text style={styles.tableCell}>{row.researchHours || 0}</Text>
                      </View>
                      {/* Status cell */}
                      <View style={styles.tableCol}>
                        <Text style={styles.tableCell}>{row.status || 'Normal'}</Text>
                      </View>
                    </>
                  )}
                </View>
              ))}
            </View>
          </View>
        )}

        {/* Conditional rendering: Show charts section if chartImages exist */}
        {chartImages && chartImages.length > 0 && (
          <View style={styles.section}>
            {/* Section title */}
            <Text style={styles.sectionTitle}>Charts</Text>
            {/* Map over chartImages array to display each chart */}
            {chartImages.map((chartImage, index) => (
              // Chart container for each image
              <View key={index} style={styles.chartContainer}>
                {/* Chart image element (base64 data URL) */}
                <Image src={chartImage} style={styles.chartImage} />
              </View>
            ))}
          </View>
        )}

        {/* Footer text at bottom of page */}
        <Text style={styles.footer}>
          {/* Footer text with organization name and timestamp */}
          Generated by SLIIT - {new Date().toLocaleString()}
        </Text>
      </Page>
    </Document>
  );
};

// Export component as default for use in other files
export default ReportPDFDocument;

