// Utility functions for exporting reports to PDF and CSV
import { pdf } from '@react-pdf/renderer';
import React from 'react';
import ReportPDFDocument from '../components/ReportPDFDocument';

/**
 * Generate and download CSV file
 */
export const downloadCSV = (reportData) => {
  const { reportType, filters, summary, tableData, chartData } = reportData;
  
  // Get report title
  const getReportTitle = () => {
    const titles = {
      'staff-workload-summary': 'Staff Workload Summary',
      'program-teaching-load': 'Program Teaching Load Report',
      'task-assignment': 'Task Assignment Report',
      'underload-overload': 'Underload/Overload Report',
      'ga-optimization': 'GA Optimization Output Report',
      'change-requests': 'Change Requests Report',
      'module-teaching': 'Module-Level Teaching Report',
      'staff-activity': 'Staff Activity Report'
    };
    return titles[reportType] || 'Report';
  };

  // Prepare CSV content
  let csvContent = '';
  
  // Header information
  csvContent += `${getReportTitle()}\n`;
  csvContent += `Academic Period: ${filters.academicPeriod || 'N/A'}\n`;
  csvContent += `Semester: ${filters.semester}\n`;
  csvContent += `Generated: ${new Date().toLocaleString()}\n`;
  csvContent += '\n';
  
  // Summary section
  csvContent += 'Summary\n';
  csvContent += `Hours Assigned,${summary.hoursAssigned}h\n`;
  csvContent += `Teaching,${summary.teachingPercent}%\n`;
  csvContent += `Admin,${summary.adminPercent}%\n`;
  csvContent += `Research,${summary.researchPercent}%\n`;
  csvContent += `Overload,${summary.overload ? 'Yes' : 'No'}\n`;
  csvContent += '\n';
  
  // Table data
  if (tableData.length > 0) {
    csvContent += 'Table Data\n';
    // Get headers based on report type
    let headers = [];
    if (reportType === 'task-assignment') {
      headers = ['Task Name', 'Staff Name', 'Domain', 'Hours per Week', 'Total Hours', 'Assignment Method'];
    } else {
      headers = ['Staff Name', 'Domain', 'Tasks', 'Total Hours', 'Teaching Hours', 'Admin Hours', 'Research Hours', 'Status'];
    }
    
    csvContent += headers.join(',') + '\n';
    
    // Add rows
    tableData.forEach(row => {
      const values = [];
      if (reportType === 'task-assignment') {
        values.push(
          `"${row.taskName || 'N/A'}"`,
          `"${row.staffName || 'N/A'}"`,
          `"${row.domain || 'N/A'}"`,
          `${row.hoursPerWeek || 0}`,
          `${row.totalHours || 0}`,
          `"${row.assignmentMethod || 'Manual'}"`
        );
      } else {
        values.push(
          `"${row.staffName || 'N/A'}"`,
          `"${row.domain || 'N/A'}"`,
          `${row.tasks || 0}`,
          `${row.totalHours || 0}`,
          `${row.teachingHours || 0}`,
          `${row.adminHours || 0}`,
          `${row.researchHours || 0}`,
          `"${row.status || 'Normal'}"`
        );
      }
      csvContent += values.join(',') + '\n';
    });
    csvContent += '\n';
  }
  
  // Chart data section - Pie Chart Data (Domain Distribution)
  if (reportType !== 'task-assignment' && (filters.displayFormat === 'chart' || filters.displayFormat === 'table+chart')) {
    csvContent += 'Chart Data - Domain Distribution (Pie Chart)\n';
    csvContent += 'Domain,Percentage\n';
    csvContent += `Teaching,${summary.teachingPercent}%\n`;
    csvContent += `Admin,${summary.adminPercent}%\n`;
    csvContent += `Research,${summary.researchPercent}%\n`;
    csvContent += '\n';
  }
  
  // Chart data section - Bar Chart Data (Hours per Week)
  if ((filters.displayFormat === 'chart' || filters.displayFormat === 'table+chart')) {
    csvContent += 'Chart Data - Hours per Week (Bar Chart)\n';
    
    // Prepare bar chart data
    let barChartData = [];
    if (reportType === 'task-assignment' && tableData.length > 0) {
      // For task assignment, use table data
      barChartData = tableData.map(item => ({
        name: item.staffName || item.taskName || 'N/A',
        hours: item.totalHours || item.hoursPerWeek || 0
      }));
    } else if (chartData && chartData.length > 0) {
      // Use provided chart data
      barChartData = chartData;
    } else if (tableData.length > 0) {
      // Generate from table data
      barChartData = tableData.map(item => ({
        name: item.staffName || 'N/A',
        hours: item.totalHours || 0
      }));
    }
    
    if (barChartData.length > 0) {
      csvContent += 'Name,Hours\n';
      barChartData.forEach(item => {
        csvContent += `"${item.name || item.staffName || item.taskName || 'N/A'}",${item.hours || item.totalHours || item.hoursPerWeek || 0}\n`;
      });
      csvContent += '\n';
    }
  }
  
  // Footer
  csvContent += `Generated by SLIIT - ${new Date().toLocaleString()}\n`;
  
  // Create blob and download
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  link.setAttribute('href', url);
  link.setAttribute('download', `${getReportTitle().replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.csv`);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

/**
 * Convert chart to image using html2canvas
 */
const convertChartToImage = async (chartElement) => {
  try {
    // Dynamic import of html2canvas
    const html2canvas = (await import('html2canvas')).default;
    
    if (!chartElement) {
      return null;
    }
    
    // Wait a moment to ensure chart is fully rendered
    await new Promise(resolve => setTimeout(resolve, 300));
    
    const canvas = await html2canvas(chartElement, {
      backgroundColor: '#ffffff',
      scale: 2,
      logging: false,
      useCORS: true,
      allowTaint: false,
      width: chartElement.offsetWidth,
      height: chartElement.offsetHeight,
    });
    return canvas.toDataURL('image/png');
  } catch (error) {
    console.error('Error converting chart to image:', error);
    return null;
  }
};

/**
 * Generate and download PDF file using @react-pdf/renderer
 */
export const downloadPDF = async (reportData, chartRefs = null) => {
  try {
    let chartImages = [];
    
    // If chart refs are provided, convert them to images
    if (chartRefs && chartRefs.length > 0) {
      for (const chartRef of chartRefs) {
        if (chartRef && chartRef.current) {
          const imageData = await convertChartToImage(chartRef.current);
          if (imageData) {
            chartImages.push(imageData);
          }
        }
      }
    }
    
    // Generate PDF blob using react-pdf/renderer
    const doc = React.createElement(ReportPDFDocument, { reportData, chartImages });
    const blob = await pdf(doc).toBlob();
    
    // Create download link
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    
    // Get report title for filename
    const getReportTitle = () => {
      const titles = {
        'staff-workload-summary': 'Staff_Workload_Summary',
        'program-teaching-load': 'Program_Teaching_Load_Report',
        'task-assignment': 'Task_Assignment_Report',
        'underload-overload': 'Underload_Overload_Report',
        'ga-optimization': 'GA_Optimization_Output_Report',
        'change-requests': 'Change_Requests_Report',
        'module-teaching': 'Module_Level_Teaching_Report',
        'staff-activity': 'Staff_Activity_Report'
      };
      return titles[reportData.reportType] || 'Report';
    };
    
    link.download = `${getReportTitle()}_${new Date().toISOString().split('T')[0]}.pdf`;
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    // Clean up
    URL.revokeObjectURL(url);
  } catch (error) {
    console.error('Error generating PDF:', error);
    // Fallback to browser print if react-pdf fails
    generatePDFWithPrint(reportData);
  }
};

/**
 * Generate PDF using jsPDF library
 */
const generatePDFWithJSPDF = (reportData, jsPDF) => {
  const { reportType, filters, summary, tableData } = reportData;
  const doc = new jsPDF('p', 'mm', 'a4');
  
  // Get report title
  const getReportTitle = () => {
    const titles = {
      'staff-workload-summary': 'Staff Workload Summary',
      'program-teaching-load': 'Program Teaching Load Report',
      'task-assignment': 'Task Assignment Report',
      'underload-overload': 'Underload/Overload Report',
      'ga-optimization': 'GA Optimization Output Report',
      'change-requests': 'Change Requests Report',
      'module-teaching': 'Module-Level Teaching Report',
      'staff-activity': 'Staff Activity Report'
    };
    return titles[reportType] || 'Report';
  };

  const title = getReportTitle();
  let yPosition = 20;
  
  // Header
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 105, yPosition, { align: 'center' });
  yPosition += 10;
  
  // Metadata
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Academic Period: ${filters.academicPeriod || 'N/A'}`, 20, yPosition);
  yPosition += 5;
  doc.text(`Semester: ${filters.semester}`, 20, yPosition);
  yPosition += 5;
  doc.text(`Generated: ${new Date().toLocaleString()}`, 20, yPosition);
  yPosition += 10;
  
  // Summary section
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Summary', 20, yPosition);
  yPosition += 7;
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Hours Assigned: ${summary.hoursAssigned}h`, 20, yPosition);
  yPosition += 5;
  doc.text(`Teaching: ${summary.teachingPercent}%`, 20, yPosition);
  yPosition += 5;
  doc.text(`Admin: ${summary.adminPercent}%`, 20, yPosition);
  yPosition += 5;
  doc.text(`Research: ${summary.researchPercent}%`, 20, yPosition);
  yPosition += 5;
  doc.text(`Overload: ${summary.overload ? 'Yes' : 'No'}`, 20, yPosition);
  yPosition += 10;
  
  // Table data
  if (tableData.length > 0) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Report Data', 20, yPosition);
    yPosition += 7;
    
    // Table headers
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    let headers = [];
    if (reportType === 'task-assignment') {
      headers = ['Task Name', 'Staff', 'Domain', 'Hrs/Week', 'Total Hrs'];
    } else {
      headers = ['Staff Name', 'Domain', 'Tasks', 'Total Hrs', 'Teaching', 'Admin', 'Research', 'Status'];
    }
    
    let xPosition = 20;
    headers.forEach((header, index) => {
      doc.text(header, xPosition, yPosition);
      xPosition += index === 0 ? 50 : 30;
    });
    yPosition += 5;
    
    // Table rows
    doc.setFont('helvetica', 'normal');
    tableData.forEach((row, index) => {
      if (yPosition > 270) {
        doc.addPage();
        yPosition = 20;
      }
      
      xPosition = 20;
      if (reportType === 'task-assignment') {
        const values = [
          row.taskName || 'N/A',
          row.staffName || 'N/A',
          row.domain || 'N/A',
          `${row.hoursPerWeek || 0}`,
          `${row.totalHours || 0}`
        ];
        values.forEach((value, idx) => {
          doc.text(String(value).substring(0, idx === 0 ? 20 : 15), xPosition, yPosition);
          xPosition += idx === 0 ? 50 : 30;
        });
      } else {
        const values = [
          row.staffName || 'N/A',
          row.domain || 'N/A',
          `${row.tasks || 0}`,
          `${row.totalHours || 0}`,
          `${row.teachingHours || 0}`,
          `${row.adminHours || 0}`,
          `${row.researchHours || 0}`,
          row.status || 'Normal'
        ];
        values.forEach((value, idx) => {
          doc.text(String(value).substring(0, idx === 0 ? 20 : 10), xPosition, yPosition);
          xPosition += idx === 0 ? 50 : 25;
        });
      }
      yPosition += 6;
    });
  }
  
  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'italic');
    doc.text(
      `Page ${i} of ${pageCount} - Generated by SLIIT`,
      105,
      287,
      { align: 'center' }
    );
  }
  
  // Save PDF
  doc.save(`${title.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`);
};

/**
 * Fallback: Generate PDF using browser print functionality
 */
const generatePDFWithPrint = (reportData) => {
  // Create a printable version
  const printWindow = window.open('', '_blank');
  const { reportType, filters, summary, tableData } = reportData;
  
  const getReportTitle = () => {
    const titles = {
      'staff-workload-summary': 'Staff Workload Summary',
      'program-teaching-load': 'Program Teaching Load Report',
      'task-assignment': 'Task Assignment Report',
      'underload-overload': 'Underload/Overload Report',
      'ga-optimization': 'GA Optimization Output Report',
      'change-requests': 'Change Requests Report',
      'module-teaching': 'Module-Level Teaching Report',
      'staff-activity': 'Staff Activity Report'
    };
    return titles[reportType] || 'Report';
  };

  let htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${getReportTitle()}</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 20px; }
        h1 { color: #1f2937; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f9fafb; font-weight: bold; }
        .summary { margin: 20px 0; }
        .summary-item { margin: 5px 0; }
        @media print {
          body { margin: 0; }
          @page { margin: 1cm; }
        }
      </style>
    </head>
    <body>
      <h1>${getReportTitle()}</h1>
      <div class="summary">
        <p><strong>Academic Period:</strong> ${filters.academicPeriod || 'N/A'}</p>
        <p><strong>Semester:</strong> ${filters.semester}</p>
        <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
      </div>
      <div class="summary">
        <h3>Summary</h3>
        <div class="summary-item">Hours Assigned: ${summary.hoursAssigned}h</div>
        <div class="summary-item">Teaching: ${summary.teachingPercent}%</div>
        <div class="summary-item">Admin: ${summary.adminPercent}%</div>
        <div class="summary-item">Research: ${summary.researchPercent}%</div>
        <div class="summary-item">Overload: ${summary.overload ? 'Yes' : 'No'}</div>
      </div>
  `;

  if (tableData.length > 0) {
    htmlContent += '<table><thead><tr>';
    if (reportType === 'task-assignment') {
      htmlContent += '<th>Task Name</th><th>Staff Name</th><th>Domain</th><th>Hours per Week</th><th>Total Hours</th><th>Assignment Method</th>';
    } else {
      htmlContent += '<th>Staff Name</th><th>Domain</th><th>Tasks</th><th>Total Hours</th><th>Teaching Hours</th><th>Admin Hours</th><th>Research Hours</th><th>Status</th>';
    }
    htmlContent += '</tr></thead><tbody>';
    
    tableData.forEach(row => {
      htmlContent += '<tr>';
      if (reportType === 'task-assignment') {
        htmlContent += `
          <td>${row.taskName || 'N/A'}</td>
          <td>${row.staffName || 'N/A'}</td>
          <td>${row.domain || 'N/A'}</td>
          <td>${row.hoursPerWeek || 0}h/week</td>
          <td>${row.totalHours || 0}h</td>
          <td>${row.assignmentMethod || 'Manual'}</td>
        `;
      } else {
        htmlContent += `
          <td>${row.staffName || 'N/A'}</td>
          <td>${row.domain || 'N/A'}</td>
          <td>${row.tasks || 0}</td>
          <td>${row.totalHours || 0}h</td>
          <td>${row.teachingHours || 0}h</td>
          <td>${row.adminHours || 0}h</td>
          <td>${row.researchHours || 0}h</td>
          <td>${row.status || 'Normal'}</td>
        `;
      }
      htmlContent += '</tr>';
    });
    
    htmlContent += '</tbody></table>';
  }

  htmlContent += `
      <div style="margin-top: 30px; font-size: 10px; color: #6b7280; text-align: center;">
        Generated by SLIIT - ${new Date().toLocaleString()}
      </div>
    </body>
    </html>
  `;

  printWindow.document.write(htmlContent);
  printWindow.document.close();
  
  // Wait for content to load, then trigger print
  setTimeout(() => {
    printWindow.print();
  }, 250);
};

